- name: Configurare il firewall del contro plane
  hosts: cp1
  tasks:
    - name: Allow port 22
      community.general.ufw:
        rule: allow
        port: 22    
    - name: Allow port 6443
      community.general.ufw:
        rule: allow
        port: 6443
        proto: tcp
    - name: Allow port 2379 to 2380
      community.general.ufw:
        rule: allow
        port: 2379:2380
        proto: tcp
    - name: Allow port 10250 to 10252
      community.general.ufw:
        rule: allow
        port: 10250:10252
        proto: tcp
    - name: Abilitare UFW
      community.general.ufw:
        state: enabled
# ok
