Vagrant.configure("2") do |config|

  config.vm.define "cp1" do |cp1|

    cp1.vm.box = "ubuntu/focal64"
    cp1.vm.network "public_network", ip: "192.168.1.86"

      cp1.vm.provider "virtualbox" do |v|
        v.name = "cp1"
        v.memory = 2048
        v.cpus = 2
      end
  
  end

  config.vm.define "n1" do |n1|

    n1.vm.box = "ubuntu/focal64"
    n1.vm.network "public_network", ip: "192.168.1.243"
      
      n1.vm.provider "virtualbox" do |v|
        v.name = "n1"
        v.memory = 1024
        v.cpus = 1
      end
  
  end

  config.vm.define "n2" do |n2|

    n2.vm.box = "ubuntu/focal64"
    n2.vm.network "public_network", ip: "192.168.1.252"
      
      n2.vm.provider "virtualbox" do |v|
        v.name = "n2"
        v.memory = 1024
        v.cpus = 1
      end
  
  end

  #config.vm.define "n1", autostart: false
  #config.vm.define "n2", autostart: false

end
